--- 
language: python
install: pip install -r requirements.txt --use-mirrors
python: 
- "2.6"
- "2.7"
env: 
  global: 
  - secure: |-
      ahgWHHRdu65OLx9QGXBve21/kzn1SG5kkMT041+cq+WL3H0A/Ne4DLof1vft
      j1fRxx79k4+FAASZCBIKbNJ+5j/IpUynzPiNNzZp8aRQbWeaypTpxb4ZWyNh
      rk4EZVLG2R7Wd9zEcA31RqtIvZWtSwVilFhUF7jJPB0yh0tNKmA=
  - secure: |-
      b+bvdHf6wkevs2yvgOectxeuHA4NVaUkXrhp7eI1poMHjw6/5XL7OuEIitKH
      4P7x5h7DxBcLb/l5vBN6JjYAUI64pO8bYQKjo8wmCSBnXyBOCMyNmlPVM4Ys
      x/jKllM57JuXU9l4BRYU9oU1q0amIDu0Pwppkzne6uy5cZHyxqs=
  - secure: |-
      FDjVOq4TjRdUZJa9psoOUxTSG9N8fx9woBOlUjNHmRAYd2SiJR0eR8qlaS2B
      vJfefCDLIY0QIzLs9zn/lF2SFbFe+1THbGuMo2rbJV73HKbBbh4A/PLUaoyG
      PHwyiC3FmT31diisxL6NjWwZPZPaFp2rnW9o7fgkFODcyV/RhHQ=
script: python tests.py
