--- 
install: pip install -r requirements.txt --use-mirrors
python: 
- "2.7"
language: python
env: 
  global: 
  - secure: |-
      Tk1BCg6x6dA71aOobHBdB22hWdSPsqwVy4D/5ZEZxTOFs+rEvgIy2eDdG9kc
      jz/WfBqDO3iAKN7UgZ45Kao4Qh6DsiJIL0JyKBzIHGJuZQCiovR6uFjjZ+nM
      pxQoY9/IlYO1wgcFo7qSK9jB/woox5WEJ9LJCU1O1CwRKzwLrKc=
  - secure: |-
      RYg/FBQySfwXs1roFUQ/SdNKTCIpkiHvdZ41ih2WGA3L1IG/ofU73w1zbaxD
      vpTB85AlsOSLe4KHD1L8ceBkhMf5Yu65jgsTnv0V/YGyRLnIL1fP3HmSwNHC
      b53e42gP1cUZi2Sd2DA9uiF6D4h0yjbBcluCHMd9gH7AZKOmnAI=
script: python tests.py
